[project]
name = "xero-sync"
version = "1.0.0"
dependencies = [
  "aws-lambda-powertools==3.31.1",
  "boto3==1.43.67",
  "boto3-stubs[secretsmanager]==1.43.67",
  "botocore[crt]==1.43.67",
  "dataclass-wizard==1.0.0",
  "requests==2.34.2",
  "stripe==15.4.0",
  "xero-python==15.0.0",
]
requires-python = ">= 3.13"

[project.optional-dependencies]
test = [
  "pytest==9.1.1",
  "pytest-bdd==8.1.0",
  "pytest-cov==7.1.0",
  "pytest-ruff==0.5"
]

[tool.pyright]
reportPrivateUsage = false
typeCheckingMode  = "strict"

[tool.pytest.ini_options]
pythonpath = [
  "./src",
  "./tests"
]
